version: "3.8"

services:
  app:
    build: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "9000:8000"
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@database:5432/movies
    depends_on:
      - database
      - selenium
  
  selenium:
    image: selenium/standalone-chrome
    ports:
    - 4444:4444
    restart: always
  
  chrome:
    image: selenium/node-chrome:4.1.3-20220327
    shm_size: 2gb
    depends_on:
      - selenium


  database:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
